### PR TITLE
initial app files

### LINKED ISSUE #2: Initial setup and configurations
Heroku Postgresql

### PR DESCRIPTION
**Pull request by noamoss**
Flask + SQLAlchemy initial files

### CODE REVIEW

**Comment by noamoss** [comment]
@ordavidil FYI I already set the FLASK_ENV value to "production" on the heroku server

**Comment by noamoss** [comment]
@ordavidil 

ready for review, see the local db table based on the readme.md instructions.

image

Once approved you can move on and experiment the deploy pipeline

**Comment by ordavidil** [comment]
@noamoss 
Basically, I'd like to add a test to cover the changes of this PR.

Maybe to check that we're able to CRUD `Entity` class,
what do you think?

**Comment by noamoss** [comment]
@ordavidil sure. Can you add a first test for example, so I will add the others?

**Comment by ordavidil** [comment]
@noamoss 
I've restructured the files (in the spirit of https://flask.palletsprojects.com/en/1.1.x/patterns/packages/)

be aware that you `export FLASK_APP=similarity` before running `flask run`.

**Comment by noamoss** [comment]
@ordavidil 

>be aware that you export FLASK_APP=similarity before running flask run.

Since we are already using pipenv, what about [doing so through the `.env` file](https://stackoverflow.com/questions/51227159/how-do-i-set-environment-variables-in-pipenv)?

See my recent commit, feel free to merge if approved.

**Comment by ordavidil** [comment]
> Since we are already using pipenv, what about [doing so through the `.env` file](https://stackoverflow.com/questions/51227159/how-do-i-set-environment-variables-in-pipenv)?

Seems good to me .

Did you need to install `python-dotenv`?
Trying `flask run` hint me to install it and now it works, so I've just updated the `requirements.txt` accordingly.

**Comment by ordavidil** [comment]
> Since we are already using pipenv, what about [doing so through the `.env` file](https://stackoverflow.com/questions/51227159/how-do-i-set-environment-variables-in-pipenv)?

Also, I've polished it a bit by adding `_example.env` since `.env` is part of the `.gitignore` and should probably stay as such.

**Comment by noamoss** [comment]
@ordavidil please see the failing test, following the (correct) reconstruction you made. I could reproduce the failure.
I suspect it has to do with the virtualenv / pipenv settings. Any idea?

**Comment by ordavidil** [comment]
@noamoss 
Current issue is that `flask` is not found, see the [log](https://github.com/noamoss/similarity-hub/pull/11/checks?check_run_id=1851621367#step:9:9):
image

**Comment by noamoss** [comment]
That where we were a week ago, before I messed up 😀

**Comment by ordavidil** [comment]
@noamoss 
Having some progress.
Added postgres to the tests and now it run using pipenv.

Currently the tests fail probably due to some environment variables, but this is just a first guess:
image

**Comment by noamoss** [comment]
@ordavidil did not we give up ln pipenv in favour of pyenv?

**Review by ordavidil — APPROVED** [review]

**Pull request merged**
